spring:
  profiles:
    active: zhangsan
server:
  port: 8083
aliyun:
  accessKeyId:
  accessKeySecret: 
  oss:
    endPoint: oss-cn-beijing.aliyuncs.com
    bucketName: cskaoyan
  sms:
    signName: stone4j
    templateCode: SMS_173765187
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.cskaoyan.market.db.mybatis
pagehelper:
  helper-dialect: mysql
  reasonable: true

