spring:
  profiles:
    active: zhangsan
server:
  port: 8083
aliyun:
  accessKeyId:
  accessKeySecret: 
  oss:
    endPoint: 
    bucketName: cskaoyan
  sms:
    signName: 
    templateCode: 
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.cskaoyan.market.db.mybatis
pagehelper:
  helper-dialect: mysql
  reasonable: true

